export const AGENT_COLORS = [0xE74C3C, 0xFF69B4, 0x3498DB, 0xF39C12, 0x2ECC71];

export const AGENT_PROFILES = [
  {
    name: 'Ваня',
    color: 0xE74C3C,
    speed: 4.5,
    aggression: 0.9,
    riskTaking: 0.8,
    playfulness: 0.4,
    panicDistance: 4.0,
    description: 'Агрессивный — любит догонять',
  },
  {
    name: 'Маша',
    color: 0xFF69B4,
    speed: 3.8,
    aggression: 0.3,
    riskTaking: 0.2,
    playfulness: 0.9,
    panicDistance: 7.0,
    description: 'Нервная — прячется за горкой',
  },
  {
    name: 'Коля',
    color: 0x3498DB,
    speed: 4.8,
    aggression: 0.6,
    riskTaking: 0.9,
    playfulness: 0.6,
    panicDistance: 4.5,
    description: 'Стратег — использует препятствия',
  },
  {
    name: 'Даша',
    color: 0xF39C12,
    speed: 4.2,
    aggression: 0.7,
    riskTaking: 0.5,
    playfulness: 0.8,
    panicDistance: 5.5,
    description: 'Социальная — держится рядом с другими',
  },
  {
    name: 'Петя',
    color: 0x2ECC71,
    speed: 5.2,
    aggression: 0.4,
    riskTaking: 0.3,
    playfulness: 1.0,
    panicDistance: 8.0,
    description: 'Клоун — убегает со смехом',
  },
];
